version: '3.1'

services:

  nginx:
    build: ./src/nginx
    container_name: lesson7_nginx
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - ./src/app/www:/var/www
      - ./src/nginx/logs:/etc/logs/nginx
      - ./src/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./src/php
    container_name: lesson7_php
    working_dir: /var/www
    volumes:
      - ./src/app/www:/var/www

  app:
    build: ./src/app
    container_name: lesson7_app
    command: sh /start.sh
    volumes:
    - ./src/app/www:/var/www